# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 02:23
from __future__ import unicode_literals

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='正文')),
                ('md_file', models.FileField(blank=True, upload_to=article.models.Article.get_upload_md_name, verbose_name='上传MD文章')),
                ('html_file', models.FileField(blank=True, upload_to=article.models.Article.get_html_name)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('last_edit_date', models.DateTimeField(auto_now=True, verbose_name='最后修改')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('article_status', models.IntegerField(choices=[(0, '发布'), (1, '草稿')], default=0, verbose_name='文章状态')),
                ('comment_status', models.IntegerField(choices=[(0, '开启'), (1, '禁用')], default=0, verbose_name='评论状态')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'ordering': ['-last_edit_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=article.models.Image.get_upload_img_name)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='article.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Category', verbose_name='分类'),
        ),
    ]
