# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:59
from __future__ import unicode_literals

import article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default='Default Value', max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='article',
            name='md_file',
            field=models.FileField(blank=True, upload_to=article.models.Article.get_upload_md_name, verbose_name='上传MD文件'),
        ),
    ]
