# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170317_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment_status',
        ),
    ]
