# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_comment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyuuni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='咒文')),
                ('by', models.CharField(max_length=300, verbose_name='吟唱者')),
                ('defi', models.TextField(blank=True, verbose_name='释义')),
                ('status', models.IntegerField(choices=[(0, '发布'), (1, '草稿')], default=0, verbose_name='施法状态')),
            ],
        ),
    ]
